server:
  port: 8083
  servlet:
    context-path: /PhoneBook 
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver 
    password: abc_123
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: PHNBK_LOCAL
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
